language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"

git:
  depth: 10

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available for PHP $TRAVIS_PHP_VERSION"

install:
  - composer install --prefer-dist

script: ./bin/phpspec run

